#!/bin/sh
#SBATCH --account=HPC at CU
#SBATCH --nodes=8
#SBATCH --tasks-per-node=12
#SBATCH --time=1:00:00
#SBATCH --mem-per-cpu=10gb
#SBATCH --threads-per-core=1
#SBATCH --output=stdout.out
#SBATCH --error=stderr.out

module load intel-parallel-studio/2017
ulimit -s unlimited

date
mpiexec -bootstrap slurm lmp_intel_cpu_intelmpi-aenet-2.1.0-fast-intel2017 -in input.lmp > lammps.out
date
